env:
  test
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

# http://cloud.spring.io/spring-cloud-static/Finchley.M8/single/spring-cloud.html#_customizing_default_for_all_ribbon_clients
# 查找product的负载均衡策略
product:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule